version: "3.5"

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/adrian/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/adrian/data/mariadb
                        o: bind
                        type: none

networks:
  inception:
    name: inception
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:42
    depends_on:
      - mariadb
      - wordpress
    networks:
      inception:
    ports:
      - "443:443"
    volumes:
     - wordpress:/var/www/wordpress
    env_file:
      - .env
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure
